Configure k8s container to send pull reminders as a cron job
akvo/akvo-platform pull request #218
Opened 2020-12-03 12:03 UTC by punchagan

2020-12-03 12:27 UTC, iperdomo requested changes
Minor changes

2020-12-03 12:27 UTC, iperdomo commented on k8s/zulip-pull-reminders/Dockerfile
> +RUN apk add --no-cache curl jq bash
Let's pin the packages

2020-12-03 12:27 UTC, iperdomo commented on k8s/zulip-pull-reminders/ci/deploy.sh
> +gcloud config set container/use_client_certificate True
This will fail in SemaphoreCI, we need to set it to `False`

2020-12-03 12:27 UTC, iperdomo commented on k8s/zulip-pull-reminders/ci/deploy.sh
> +gcloud components update
You can't install new gcloud components in SemaphoreCI

2020-12-03 12:42 UTC, punchagan commented on k8s/zulip-pull-reminders/ci/deploy.sh
> +gcloud config set container/use_client_certificate True
I copied this from the `flow-data-backup` script. Does this mean that script doesn't run on Semaphore at all? :see_no_evil:

2020-12-03 12:43 UTC, punchagan commented on k8s/zulip-pull-reminders/Dockerfile
> +RUN apk add --no-cache curl jq bash
Sure, I guess you want us to pin the docker image version too?

2020-12-03 12:52 UTC, dlebrero commented on k8s/zulip-pull-reminders/Dockerfile
> +RUN apk add --no-cache curl jq bash
Yes

2020-12-03 12:53 UTC, dlebrero commented on k8s/zulip-pull-reminders/ci/deploy.sh
> +gcloud config set container/use_client_certificate True
This project is still in Travis. If we want to move to semaphore, lets do that as a separate piece of work

2020-12-03 13:59 UTC, iperdomo commented on k8s/zulip-pull-reminders/ci/deploy.sh
> +gcloud config set container/use_client_certificate True
I didn't remembered that this was still on Travis, agree with @dlebrero moving to Semaphore is a different effort

2020-12-03 16:50 UTC, punchagan commented on k8s/zulip-pull-reminders/ci/deploy.sh
> +gcloud config set container/use_client_certificate True
Okay, I'm going to leave this for later, then.

2020-12-03 16:50 UTC, punchagan commented on k8s/zulip-pull-reminders/ci/deploy.sh
> +gcloud components update
Leaving this for later, assuming it works on Travis.

2020-12-03 16:59 UTC, punchagan commented on k8s/zulip-pull-reminders/Dockerfile
> +RUN apk add --no-cache curl jq bash
Done!

2020-12-03 17:09 UTC, iperdomo approved these changes

2020-12-04 10:54 UTC, iperdomo approved these changes

2020-12-07 08:36 UTC, merged